# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-02 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(choices=[(b'Checked In', b'Patient Checked Into Room'), (b'Arrived', b'Patient Arrived'), (b'', b'Appointment Scheduled'), (b'Confirmed', b'Appointment Confirmed'), (b'In Session', b'Appointment In Session'), (b'Complete', b'Appointment Complete'), (b'Rescheduled', b'Appointment Rescheduled'), (b'Canceled', b'Appointment Canceled')], default=b'Confirmed', max_length=32)),
                ('reason', models.CharField(default=b'', max_length=200)),
                ('exam_room', models.CharField(default=b'1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waiting_start', models.DateTimeField(blank=True, null=True)),
                ('waiting_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patient_photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drchrono.Patient'),
        ),
    ]
